name: Test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        valkey-version:
          - "latest"
          - "alpine"
          - "bookworm"
    steps:
      - uses: actions/checkout@v4
      - name: Install redis-cli
        run: sudo apt install -y redis-tools
      - name: Deploy Valkey ${{ matrix.valkey-version }}
        uses: ./
        with:
          host port: ${{ matrix.host-port }}
      - name: Test
        run: |
          pong=$(redis-cli  ping)
          if [ "$pong" != "PONG" ]; then
            echo "Test command failed. Check that the container is running"
            exit 1
          fi
      
